server.port=4000

spring.datasource.url=${DB_URI:${DB_URL}}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

clerk.issuer-uri=https://top-opossum-75.clerk.accounts.dev
clerk.jwk-set-uri=${clerk.issuer-uri}/.well-known/jwks.json

cloudinary.cloud-name=${CLDN_NAME}
cloudinary.api-key=${CLDN_API_KEY}
cloudinary.api-secret=${CLDN_API_SECRET}

# Límite de tamaño para multipart (ajusta según necesites)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=40MB